import type { Metadata } from "next";
import Navbar from "./(components)/(navbar)/page";
import "./layout.css";

export const metadata: Metadata = {
  title: "Book Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
         
          {children}
        </main>
      </body>
    </html>
  );
}
