import type { Metadata } from "next";

import "./layout.css";
import { AuthProvider } from "./authContext/authContext";

export const metadata: Metadata = {
  title: "Book Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
