import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "@/authContext";
import { NameSpotsProvider } from "@/context/NameSpotsContext";
import { NearbySpotsProvider } from "@/context/NearbySpotsContext";
import { SearchModeProvider } from "@/context/SearchModeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${inter.variable} ${roboto.variable} antialiased bg-gray-100`}
      >
        <AuthProvider>
          <NameSpotsProvider>
            <NearbySpotsProvider>
              <SearchModeProvider>
                <Navbar />

                {children}
              </SearchModeProvider>
            </NearbySpotsProvider>
          </NameSpotsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
